#!/bin/sh

echo
echo "[dep2] Let me check if the test thing is installed.."

while ! sv -w1 check test &> /dev/null; do
  sleep 5
done

echo "[dep2] Okay, the test thing is installed, but I also need dep1 :("

while ! sv -w1 check dep1 &> /dev/null; do
  sleep 5
done

echo "[dep2] Finally dep1 has started, so here I go as well!"

echo 1 > /tmp/dep2

exec tail -f -n0 /root/.bashrc
